# Generated by Django 5.0.2 on 2024-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_link',
            field=models.URLField(default=''),
        ),
    ]
